### PR TITLE
Test coverage

### PR DESCRIPTION
**Pull request by GraceTsang**
- Add Travis CI build
- Add "make debug" for running gcov on all files, "make release" for optimization
- Add unit tests for nginx_config_parser
- Changed the nginx config parser so that it passes said tests

### CODE REVIEW

**Comment by zxxia** [comment]
I think we can add also -Werror flag in Makefile since Trevor and James mentioned in class.

**Comment by GraceTsang** [comment]
As it turns out, having -Werror and also -pedantic is kinda annoying. I'm not sure if -pedantic is recommended, but it basically turns a lot of things into warnings...which -Werror turns into errors. Basically it makes the build look super ugly unless you go and fix every little thing. Do you think we need to had -pedantic?

**Comment by kevinwu127** [comment]
I'm sure -pedantic isn't required. we can probably leave that out

**Comment by zxxia** [comment]
I removed it.

**Comment by zxxia** [comment]
Hi Kevin. Can you take a look at .travis.yml. I did some modification and I don't know why Travis CI build failed.

**Comment by zxxia** [comment]
Oh, I got a typo in .travis.yml.

**Pull request merged**
