### PR TITLE
Added and integrated config_parser to project.

### PR DESCRIPTION
**Pull request by kevinwu127**
Currently can parse a given command-line config file, but cannot input to server constructor yet. Working on that at the moment.

### CODE REVIEW

**Comment by kevinwu127** [comment]
Can now instantiate a local webserver that serves the project directory to localhost:3000

**Comment by zxxia** [comment]
Hi Kevin. I looked through all commits you made in the past few days. The main part you added is Server Struct in main.cpp and this struct is responsible for getting the parsed parameters from NginxConfig Parser you wrote and passing them to HTTP Server. Please correct me if I am wrong.

**Comment by kevinwu127** [comment]
Yup! That struct is pretty much the only thing that links them together. Also, my parsing function in main.cpp is also really ugly. I guess the one thing that I would fix would be to make it recursive. What do you think? Do you wanna work on that?

**Comment by zxxia** [comment]
It may also be a good idea to rename the executable file "server" to "webserver" since "webserver" is more consistent with the command in spec.

**Comment by kevinwu127** [comment]
sure! I'll make sure to include change in the Makefile for the next commit :)

**Comment by zxxia** [comment]
Is the reason you would like to make parsing function recursive that there exists nested blocks like "server { location {blah blah}}" in config file?

**Comment by kevinwu127** [comment]
Yes I would like to make the parsing function more readable and robust. The current solution is naive and using brute force

**Comment by zxxia** [comment]
yeah I agree with you. We can work on that. Is the assignment going to due at 11:59pm today?

**Comment by kevinwu127** [comment]
Pretty sure it's due tomorrow night at 11:59PM. I'll go ahead and merge this branch then so you can work on recursing the function. Thanks!

**Pull request merged**
