### PR TITLE
Echo

### PR DESCRIPTION
**Pull request by GraceTsang**
- Make request_handler echo request in response
- Server should no longer return 404s
- Change server config
- Server is now at 127.0.0.1

### CODE REVIEW

**Review by kevinwu127 — COMMENTED** [review]
This looks great! Thanks so much for the help, Grace :). Btw, I actually need the host address to be 0.0.0.0 for my VM to work, would you mind changing it back? It actually also makes it revealed at local host the same anyways :)

**Comment by zxxia** [comment]
I run the server and it is really impressive. Thank you very much Grace. Probably README needs some modifications but it is not very important. And I think it is good to merge.

**Comment by GraceTsang** [comment]
Alright, so I changed host back to 0.0.0.0. Could you try running it now, @kevinwu127 ?

**Comment by kevinwu127** [comment]
As long as you can run it on your machine, I should be fine! Sorry I'm at the career fair cuz I need a job :(

**Comment by zxxia** [comment]
I just want to make sure I run it correctly. The following is the content I see in the browser. Is it correct?

GET / HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive

**Comment by GraceTsang** [comment]
Haha good luck with the job search~ It's fine if you run it later though, as long as it's before midnight today.

**Comment by kevinwu127** [comment]
GET / HTTP/1.1
TE: deflate,gzip;q=0.3
Connection: TE, close
Host: localhost:3000
User-Agent: lwp-request/6.03 libwww-perl/6.05

that's what i get in my console. I can't get it to display on my browser, however.. It just hangs :/

**Comment by GraceTsang** [comment]
That's odd...Could it have to do with your VM? What are you using to develop? For reference, I'm developing on Windows. It works in console, Chrome, and Edge for me....

**Comment by kevinwu127** [comment]
So I develop with Vagrant on a Windows machine, but I'm doing some fancy porting to make it show natively. If it works with your machines, I'm sure it's fine. The problem is most definitely with my environment :)

**Comment by GraceTsang** [comment]
Okay. Is it ready to merge, then?

**Comment by zxxia** [comment]
Sounds good to me.

**Comment by kevinwu127** [comment]
yup! Go ahead 👍

**Pull request merged**
