### PR TITLE
File server

### PR DESCRIPTION
**Pull request by zxxia**
Hi guys. I created a base class called request_handler and simplified the code in request_handler_echo.

I also created a request handler for file request but I haven't fully understood how to put two servers together based on "/echo" and "/static" in url according to spec. 

The reason of autobuild failure is that the class name changed.

### CODE REVIEW

**Comment by kevinwu127** [comment]
I want to move to remove request_handler_echo.cpp and all related files. We are not going to use the inheritance approach for now and just create an request_handler API model instead that acts as a rudimentary Router, similar to how Node does it.

**Comment by zxxia** [comment]
The spec requires two request handlers inheriting from a base class. I am not sure if it is ok not to use inheritance.

**Comment by kevinwu127** [comment]
Making two classes would result in a lot of duplicate code. It wouldn't be very good coding style I believe... When the echo server requires more functionality, we can split it in two classes, but for now, I would like to conform to a general standard of reducing duplicate code. Thanks!

**Comment by kevinwu127** [comment]
Please review my changes and confirm that it works on your machines.

**Pull request merged**
